"""MySQL Data Exporter"""

import subprocess
import json
import csv
from typing import List, Optional
import pymysql
from pymysql.cursors import DictCursor


class MySQLExporter:
    """Export data from MySQL database"""

    def __init__(self, host: str, user: str, password: str, database: str, port: int = 3306):
        self.host = host
        self.user = user
        self.password = password
        self.database = database
        self.port = port
        self.connection = None

    def _connect(self):
        """Establish database connection"""
        if not self.connection:
            self.connection = pymysql.connect(
                host=self.host,
                user=self.user,
                password=self.password,
                database=self.database,
                port=self.port,
                charset='utf8mb4',
                cursorclass=DictCursor
            )

    def _disconnect(self):
        """Close database connection"""
        if self.connection:
            self.connection.close()
            self.connection = None

    def export_sql(self, tables: List[str], output_file: str, where_conditions: dict = None) -> bool:
        """Export tables as SQL script with optional WHERE conditions

        Args:
            tables: List of table names to export
            output_file: Output SQL file path
            where_conditions: Dict mapping table names to WHERE clause strings
                             e.g., {'XDR_ASSET': 'asset_id IN (1,2,3)'}
        """
        try:
            self._connect()
            cursor = self.connection.cursor()

            with open(output_file, 'w', encoding='utf-8') as f:
                f.write("-- AIXDR Data Export\n")
                f.write("-- Generated by AIXDR Data Exporter\n\n")

                for table in tables:
                    # Build query with optional WHERE clause
                    query = f"SELECT * FROM {table}"
                    if where_conditions and table in where_conditions:
                        query += f" WHERE {where_conditions[table]}"

                    # Get data
                    cursor.execute(query)
                    rows = cursor.fetchall()

                    if rows:
                        f.write(f"\n-- Table: {table}\n")
                        # Get column names
                        cursor.execute(f"DESCRIBE {table}")
                        columns_info = cursor.fetchall()
                        columns = [col['Field'] for col in columns_info]

                        # Generate INSERT statements
                        for row in rows:
                            values = []
                            for col in columns:
                                val = row.get(col)
                                if val is None:
                                    values.append("NULL")
                                elif isinstance(val, bool):
                                    values.append("1" if val else "0")
                                elif isinstance(val, (int, float)):
                                    values.append(str(val))
                                elif hasattr(val, 'isoformat'):  # datetime objects
                                    # PostgreSQL uses space instead of 'T' between date and time
                                    values.append(f"'{val.isoformat().replace('T', ' ')}'")
                                else:
                                    # Properly escape string values for SQL
                                    str_val = str(val)
                                    # Escape backslashes first
                                    str_val = str_val.replace('\\', '\\\\')
                                    # Escape single quotes
                                    str_val = str_val.replace("'", "''")
                                    # Escape null bytes
                                    str_val = str_val.replace('\x00', '\\0')
                                    values.append(f"'{str_val}'")

                            col_names = ", ".join([f'`{c}`' for c in columns])
                            values_str = ", ".join(values)
                            f.write(f'INSERT INTO `{table}` ({col_names}) VALUES ({values_str});\n')

            self._disconnect()
            return True
        except Exception as e:
            print(f"Error exporting to SQL: {e}")
            return False

    def export_csv(self, table: str, output_file: str) -> bool:
        """Export single table as CSV"""
        try:
            self._connect()
            cursor = self.connection.cursor()

            # Get columns
            cursor.execute(f"DESCRIBE {table}")
            columns_info = cursor.fetchall()
            columns = [col['Field'] for col in columns_info]

            # Get data
            cursor.execute(f"SELECT * FROM {table}")
            rows = cursor.fetchall()

            # Write CSV
            with open(output_file, 'w', newline='', encoding='utf-8') as f:
                writer = csv.DictWriter(f, fieldnames=columns)
                writer.writeheader()
                writer.writerows(rows)

            self._disconnect()
            return True
        except Exception as e:
            print(f"Error exporting to CSV: {e}")
            return False

    def export_json(self, table: str, output_file: str) -> bool:
        """Export table as JSON Lines format"""
        try:
            self._connect()
            cursor = self.connection.cursor()

            cursor.execute(f"SELECT * FROM {table}")
            rows = cursor.fetchall()

            with open(output_file, 'w', encoding='utf-8') as f:
                for row in rows:
                    # Convert datetime objects to strings
                    json_row = {}
                    for key, val in row.items():
                        if val is None:
                            json_row[key] = None
                        elif hasattr(val, 'isoformat'):
                            json_row[key] = val.isoformat()
                        else:
                            json_row[key] = val

                    f.write(json.dumps(json_row) + '\n')

            self._disconnect()
            return True
        except Exception as e:
            print(f"Error exporting to JSON: {e}")
            return False

    def get_table_info(self, table: str) -> dict:
        """Get table information (row count, columns)"""
        try:
            self._connect()
            cursor = self.connection.cursor()

            # Row count
            cursor.execute(f"SELECT COUNT(*) as count FROM {table}")
            row_count = cursor.fetchone()['count']

            # Columns
            cursor.execute(f"DESCRIBE {table}")
            columns = cursor.fetchall()

            self._disconnect()

            return {
                'table': table,
                'row_count': row_count,
                'columns': len(columns),
                'column_details': columns
            }
        except Exception as e:
            print(f"Error getting table info: {e}")
            return None

    def list_tables(self) -> List[str]:
        """List all tables in database"""
        try:
            self._connect()
            cursor = self.connection.cursor()

            cursor.execute(f"SHOW TABLES FROM {self.database}")
            tables = [row[f'Tables_in_{self.database}'] for row in cursor.fetchall()]

            self._disconnect()
            return tables
        except Exception as e:
            print(f"Error listing tables: {e}")
            return []
