"""PostgreSQL Data Exporter - Export data with cascading relationships"""

from typing import List, Dict, Set
import psycopg2
from psycopg2.extras import RealDictCursor


class PostgreSQLExporter:
    """Export asset data with all related tables from PostgreSQL database"""

    def __init__(self, host: str, user: str, password: str, database: str, port: int = 5432):
        self.host = host
        self.user = user
        self.password = password
        self.database = database
        self.port = port
        self.connection = None

    def _connect(self):
        """Establish database connection"""
        if not self.connection:
            self.connection = psycopg2.connect(
                host=self.host,
                user=self.user,
                password=self.password,
                dbname=self.database,
                port=self.port,
                cursor_factory=RealDictCursor
            )

    def _disconnect(self):
        """Close database connection"""
        if self.connection:
            self.connection.close()
            self.connection = None

    def export_by_asset_ids(self, asset_ids: List[int], output_file: str) -> bool:
        """Export XDR asset data with all related tables by asset IDs

        Tables exported:
        - xdr_asset: Main asset table (filtered by asset_id)
        - xdr_asset_ip: Asset IPs (filtered by asset_id)
        - xdr_asset_vuln: Asset vulnerabilities (filtered by asset_id)
        - xdr_risk_port: Risk ports (filtered by asset_id)
        - xdr_weak_password: Weak passwords (filtered by device_id from xdr_asset)

        Args:
            asset_ids: List of asset IDs to export
            output_file: Output SQL file path

        Returns:
            bool: True if export successful
        """
        try:
            self._connect()
            cursor = self.connection.cursor()

            # Convert asset IDs to SQL-safe format (PostgreSQL uses lowercase table names)
            asset_id_str = ','.join(str(aid) for aid in asset_ids)

            with open(output_file, 'w', encoding='utf-8') as f:
                f.write("-- AIXDR PostgreSQL Data Export\n")
                f.write("-- Generated by AIXDR Data Exporter\n")
                f.write(f"-- Asset IDs: {asset_id_str}\n\n")

                # Table structure and export order (PostgreSQL uses lowercase table names)
                tables_config = {
                    'xdr_asset': {
                        'where': f'asset_id IN ({asset_id_str})',
                        'get_related': self._get_device_ids
                    },
                    'xdr_asset_ip': {
                        'where': f'asset_id IN ({asset_id_str})',
                        'get_related': None
                    },
                    'xdr_asset_vuln': {
                        'where': f'asset_id IN ({asset_id_str})',
                        'get_related': None
                    },
                    'xdr_risk_port': {
                        'where': f'asset_id IN ({asset_id_str})',
                        'get_related': None
                    }
                }

                # First pass: export main tables
                device_ids: Set[str] = set()

                for table_name, config in tables_config.items():
                    print(f"Exporting {table_name}...")

                    # Check if table exists
                    if not self._table_exists(cursor, table_name):
                        print(f"  Warning: Table {table_name} does not exist, skipping...")
                        continue

                    # Get data
                    query = f"SELECT * FROM {table_name}"
                    if config['where']:
                        query += f" WHERE {config['where']}"

                    cursor.execute(query)
                    rows = cursor.fetchall()

                    # Collect device IDs if this is xdr_asset table
                    if table_name == 'xdr_asset':
                        for row in rows:
                            device_id = row.get('device_id')
                            if device_id:
                                device_ids.add(device_id)

                    # Generate INSERT statements
                    if rows:
                        f.write(f"\n-- Table: {table_name}\n")
                        # Get column names from cursor description
                        columns = [desc[0] for desc in cursor.description]

                        for row in rows:
                            values = self._row_to_sql_values(row, columns)
                            col_names = ", ".join([f'"{c}"' for c in columns])
                            values_str = ", ".join(values)
                            f.write(f'INSERT INTO "{table_name}" ({col_names}) VALUES ({values_str});\n')

                # Second pass: export xdr_weak_password with collected device_ids
                if device_ids:
                    print("Exporting xdr_weak_password...")
                    # Quote string device_ids for SQL IN clause
                    device_id_str = ','.join(f"'{did}'" for did in device_ids)

                    try:
                        if self._table_exists(cursor, 'xdr_weak_password'):
                            # Get weak passwords by device_id
                            query = f"SELECT * FROM xdr_weak_password WHERE device_id IN ({device_id_str})"
                            cursor.execute(query)
                            rows = cursor.fetchall()

                            if rows:
                                f.write(f"\n-- Table: xdr_weak_password\n")
                                columns = [desc[0] for desc in cursor.description]

                                for row in rows:
                                    values = self._row_to_sql_values(row, columns)
                                    col_names = ", ".join([f'"{c}"' for c in columns])
                                    values_str = ", ".join(values)
                                    f.write(f'INSERT INTO "xdr_weak_password" ({col_names}) VALUES ({values_str});\n')
                        else:
                            print("  Warning: Table xdr_weak_password does not exist, skipping...")
                    except Exception as e:
                        print(f"Warning: Could not export xdr_weak_password: {e}")

            self._disconnect()
            return True

        except Exception as e:
            print(f"Error exporting from PostgreSQL: {e}")
            import traceback
            traceback.print_exc()
            return False

    def _table_exists(self, cursor, table_name: str) -> bool:
        """Check if a table exists in the database (PostgreSQL uses lowercase)"""
        try:
            cursor.execute(
                "SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_name = %s)",
                (table_name.lower(),)
            )
            return cursor.fetchone()['exists']
        except Exception:
            return False

    def _get_device_ids(self, cursor, asset_ids: List[int]) -> Set[str]:
        """Get device IDs from xdr_asset table"""
        device_ids: Set[str] = set()
        asset_id_str = ','.join(str(aid) for aid in asset_ids)

        try:
            cursor.execute(
                f"SELECT DISTINCT device_id FROM xdr_asset WHERE asset_id IN ({asset_id_str}) AND device_id IS NOT NULL"
            )
            results = cursor.fetchall()

            for row in results:
                device_id = row.get('device_id')
                if device_id:
                    device_ids.add(device_id)
        except Exception as e:
            print(f"Error getting device IDs: {e}")

        return device_ids

    def _row_to_sql_values(self, row: dict, columns: List[str]) -> List[str]:
        """Convert row data to SQL value strings (PostgreSQL compatible)"""
        values = []
        for col in columns:
            val = row.get(col)
            if val is None:
                values.append("NULL")
            elif isinstance(val, bool):
                values.append("TRUE" if val else "FALSE")
            elif isinstance(val, (int, float)):
                values.append(str(val))
            elif hasattr(val, 'isoformat'):  # datetime objects
                # PostgreSQL uses space instead of 'T' between date and time
                values.append(f"'{val.isoformat().replace('T', ' ')}'")
            else:
                # Properly escape string values for PostgreSQL
                str_val = str(val)
                # Escape single quotes by doubling them
                str_val = str_val.replace("'", "''")
                # Escape backslashes (PostgreSQL uses E'' for escaped strings)
                str_val = str_val.replace('\\', '\\\\')
                # Escape null bytes
                str_val = str_val.replace('\x00', '\\0')
                values.append(f"'{str_val}'")
        return values

    def get_export_summary(self, asset_ids: List[int]) -> dict:
        """Get summary of data to be exported"""
        try:
            self._connect()
            cursor = self.connection.cursor()

            asset_id_str = ','.join(str(aid) for aid in asset_ids)
            summary = {
                'asset_ids': asset_ids,
                'tables': {}
            }

            # Count rows in each table
            tables = [
                ('xdr_asset', f"asset_id IN ({asset_id_str})"),
                ('xdr_asset_ip', f"asset_id IN ({asset_id_str})"),
                ('xdr_asset_vuln', f"asset_id IN ({asset_id_str})"),
                ('xdr_risk_port', f"asset_id IN ({asset_id_str})")
            ]

            device_ids: Set[str] = set()

            for table_name, where_clause in tables:
                try:
                    if not self._table_exists(cursor, table_name):
                        summary['tables'][table_name] = 0
                        continue

                    query = f"SELECT COUNT(*) as count FROM {table_name} WHERE {where_clause}"
                    cursor.execute(query)
                    result = cursor.fetchone()
                    count = result['count'] if result else 0
                    summary['tables'][table_name] = count

                    # Collect device_ids from xdr_asset
                    if table_name == 'xdr_asset':
                        cursor.execute(f"SELECT DISTINCT device_id FROM {table_name} WHERE {where_clause} AND device_id IS NOT NULL")
                        for row in cursor.fetchall():
                            device_id = row.get('device_id')
                            if device_id:
                                device_ids.add(device_id)
                except Exception as e:
                    print(f"Warning: Could not count {table_name}: {e}")
                    summary['tables'][table_name] = 0

            # Count xdr_weak_password
            if device_ids:
                try:
                    if self._table_exists(cursor, 'xdr_weak_password'):
                        device_id_quoted = ','.join(f"'{did}'" for did in device_ids)
                        query = f"SELECT COUNT(*) as count FROM xdr_weak_password WHERE device_id IN ({device_id_quoted})"
                        cursor.execute(query)
                        result = cursor.fetchone()
                        summary['tables']['xdr_weak_password'] = result['count'] if result else 0
                    else:
                        summary['tables']['xdr_weak_password'] = 0
                except Exception as e:
                    print(f"Warning: Could not count xdr_weak_password: {e}")
                    summary['tables']['xdr_weak_password'] = 0

            self._disconnect()
            return summary

        except Exception as e:
            print(f"Error getting export summary: {e}")
            return {'error': str(e)}