"""Related Tables Exporter - Export data with cascading relationships"""

from typing import List, Dict, Set
import pymysql
from pymysql.cursors import DictCursor


class RelatedTablesExporter:
    """Export asset data with cascading relationships from multiple related tables"""

    def __init__(self, host: str, user: str, password: str, database: str, port: int = 3306):
        self.host = host
        self.user = user
        self.password = password
        self.database = database
        self.port = port
        self.connection = None

    def _connect(self):
        """Establish database connection"""
        if not self.connection:
            self.connection = pymysql.connect(
                host=self.host,
                user=self.user,
                password=self.password,
                database=self.database,
                port=self.port,
                charset='utf8mb4',
                cursorclass=DictCursor
            )

    def _disconnect(self):
        """Close database connection"""
        if self.connection:
            self.connection.close()
            self.connection = None

    def export_by_asset_ids(self, asset_ids: List[int], output_file: str) -> bool:
        """Export XDR asset data with all related tables by asset IDs

        Tables exported:
        - XDR_ASSET: Main asset table (filtered by asset_id)
        - XDR_ASSET_IP: Asset IPs (filtered by asset_id)
        - XDR_ASSET_VULN: Asset vulnerabilities (filtered by asset_id)
        - XDR_RISK_PORT: Risk ports (filtered by asset_id)
        - XDR_WEAK_PASSWORD: Weak passwords (filtered by device_id from XDR_ASSET)

        Args:
            asset_ids: List of asset IDs to export
            output_file: Output SQL file path

        Returns:
            bool: True if export successful
        """
        try:
            self._connect()
            cursor = self.connection.cursor()

            # Convert asset IDs to SQL-safe format
            asset_id_str = ','.join(str(aid) for aid in asset_ids)

            with open(output_file, 'w', encoding='utf-8') as f:
                f.write("-- AIXDR Data Export with Related Tables\n")
                f.write("-- Generated by AIXDR Data Exporter\n")
                f.write(f"-- Asset IDs: {asset_id_str}\n\n")

                # Table structure and export order
                tables_config = {
                    'XDR_ASSET': {
                        'where': f'asset_id IN ({asset_id_str})',
                        'get_related': self._get_device_ids
                    },
                    'XDR_ASSET_IP': {
                        'where': f'asset_id IN ({asset_id_str})',
                        'get_related': None
                    },
                    'XDR_ASSET_VULN': {
                        'where': f'asset_id IN ({asset_id_str})',
                        'get_related': None
                    },
                    'XDR_RISK_PORT': {
                        'where': f'asset_id IN ({asset_id_str})',
                        'get_related': None
                    }
                }

                # First pass: export main tables
                device_ids: Set[int] = set()

                for table_name, config in tables_config.items():
                    print(f"Exporting {table_name}...")

                    # Get data
                    query = f"SELECT * FROM {table_name}"
                    if config['where']:
                        query += f" WHERE {config['where']}"

                    cursor.execute(query)
                    rows = cursor.fetchall()

                    # Collect device IDs if this is XDR_ASSET table
                    if table_name == 'XDR_ASSET':
                        for row in rows:
                            device_id = row.get('DEVICE_ID')
                            if device_id:
                                device_ids.add(device_id)

                    # Generate INSERT statements
                    if rows:
                        cursor.execute(f"DESCRIBE {table_name}")
                        columns_info = cursor.fetchall()
                        columns = [col['Field'] for col in columns_info]

                        for row in rows:
                            values = self._row_to_sql_values(row, columns)
                            col_names = ", ".join([f'"{c.lower()}"' for c in columns])
                            values_str = ", ".join(values)
                            f.write(f'INSERT INTO "{table_name.lower()}" ({col_names}) VALUES ({values_str});\n')

                # Second pass: export XDR_WEAK_PASSWORD with collected device_ids
                if device_ids:
                    print("Exporting XDR_WEAK_PASSWORD...")
                    # Quote string device_ids for SQL IN clause
                    device_id_str = ','.join(f"'{did}'" for did in device_ids)

                    try:
                        # Get weak passwords by device_id
                        query = f"SELECT * FROM XDR_WEAK_PASSWORD WHERE device_id IN ({device_id_str})"
                        cursor.execute(query)
                        rows = cursor.fetchall()

                        if rows:
                            f.write(f"\n-- Table: XDR_WEAK_PASSWORD\n")
                            cursor.execute("DESCRIBE XDR_WEAK_PASSWORD")
                            columns_info = cursor.fetchall()
                            columns = [col['Field'] for col in columns_info]

                            for row in rows:
                                values = self._row_to_sql_values(row, columns)
                                col_names = ", ".join([f'"{c.lower()}"' for c in columns])
                                values_str = ", ".join(values)
                                f.write(f'INSERT INTO "xdr_weak_password" ({col_names}) VALUES ({values_str});\n')
                    except Exception as e:
                        print(f"Warning: Could not export XDR_WEAK_PASSWORD: {e}")

            self._disconnect()
            return True

        except Exception as e:
            print(f"Error exporting related tables: {e}")
            return False

    def _get_device_ids(self, cursor, asset_ids: List[int]) -> Set[int]:
        """Get device IDs from XDR_ASSET table"""
        device_ids: Set[int] = set()
        asset_id_str = ','.join(str(aid) for aid in asset_ids)

        try:
            cursor.execute(f"SELECT DISTINCT device_id FROM XDR_ASSET WHERE asset_id IN ({asset_id_str}) AND device_id IS NOT NULL")
            results = cursor.fetchall()

            for row in results:
                device_id = row.get('device_id')
                if device_id:
                    device_ids.add(device_id)
        except Exception as e:
            print(f"Error getting device IDs: {e}")

        return device_ids

    def _row_to_sql_values(self, row: dict, columns: List[str]) -> List[str]:
        """Convert row data to SQL value strings"""
        values = []
        for col in columns:
            val = row.get(col)
            if val is None:
                values.append("NULL")
            elif isinstance(val, bool):
                values.append("1" if val else "0")
            elif isinstance(val, (int, float)):
                values.append(str(val))
            elif hasattr(val, 'isoformat'):  # datetime objects
                # PostgreSQL uses space instead of 'T' between date and time
                values.append(f"'{val.isoformat().replace('T', ' ')}'")
            else:
                # Properly escape string values
                # Escape backslashes first, then single quotes and other special chars
                str_val = str(val)
                # Escape backslashes
                str_val = str_val.replace('\\', '\\\\')
                # Escape single quotes
                str_val = str_val.replace("'", "''")
                # Escape double quotes (for safety)
                str_val = str_val.replace('"', '\\"')
                # Escape null bytes
                str_val = str_val.replace('\x00', '\\0')
                values.append(f"'{str_val}'")
        return values

    def get_export_summary(self, asset_ids: List[int]) -> dict:
        """Get summary of data to be exported"""
        try:
            self._connect()
            cursor = self.connection.cursor()

            asset_id_str = ','.join(str(aid) for aid in asset_ids)
            asset_id_quoted = ','.join(f"'{aid}'" for aid in asset_ids)
            summary = {
                'asset_ids': asset_ids,
                'tables': {}
            }

            # Count rows in each table (asset_id is stored as string; use quoted list)
            tables = [
                ('XDR_ASSET', f"asset_id IN ({asset_id_quoted})"),
                ('XDR_ASSET_IP', f"asset_id IN ({asset_id_quoted})"),
                ('XDR_ASSET_VULN', f"asset_id IN ({asset_id_quoted})"),
                ('XDR_RISK_PORT', f"asset_id IN ({asset_id_quoted})")
            ]

            device_ids: Set[int] = set()

            for table_name, where_clause in tables:
                try:
                    query = f"SELECT COUNT(*) as count FROM {table_name} WHERE {where_clause}"
                    cursor.execute(query)
                    result = cursor.fetchone()
                    count = result['count'] if result else 0
                    summary['tables'][table_name] = count

                    # Collect device_ids from XDR_ASSET
                    if table_name == 'XDR_ASSET':
                        cursor.execute(f"SELECT DISTINCT device_id FROM {table_name} WHERE {where_clause} AND device_id IS NOT NULL")
                        for row in cursor.fetchall():
                            device_id = row.get('device_id')
                            if device_id:
                                device_ids.add(device_id)
                except Exception as e:
                    print(f"Warning: Could not count {table_name}: {e}")
                    summary['tables'][table_name] = 0

            # Count XDR_WEAK_PASSWORD
            if device_ids:
                try:
                    device_id_quoted = ','.join(f"'{did}'" for did in device_ids)
                    query = f"SELECT COUNT(*) as count FROM XDR_WEAK_PASSWORD WHERE device_id IN ({device_id_quoted})"
                    cursor.execute(query)
                    result = cursor.fetchone()
                    summary['tables']['XDR_WEAK_PASSWORD'] = result['count'] if result else 0
                except Exception as e:
                    print(f"Warning: Could not count XDR_WEAK_PASSWORD: {e}")
                    summary['tables']['XDR_WEAK_PASSWORD'] = 0

            self._disconnect()
            return summary

        except Exception as e:
            print(f"Error getting export summary: {e}")
            return {'error': str(e)}
